### ISSUE TITLE
[RFC] Support latest Symfony LTS in master branch

### ISSUE THREAD

**Issue by ajgarlag** [bestit/flagception-bundle#81]
Last week I proposed PR #80 to allow checking for multiple features in route definition. The problem is that I need this in a Symfony 4.4 (LTS) project, so I proposed to merge the PR with the `3.x` branch.

Once the PR was merged, a new `3.6.0` version was tagged and now the `3.x` branch has more features that the `master` branch. 

To avoid this, I think master branch should always support latest Symfony LTS version.

WDYT?

**Comment by migo315** [comment]
The problem was that we could not get support for Symfony 4 and Symfony 5 in one branch. Therefore we have the 3.x branch (and 3.x version) for everything up to Symfony 4.4 and the master branch for everything from Symfony 5 on.

The "future" is actually Symfony 5 and coming versions. So it fits that the master is focused on this version. 

Since we cannot currently maintain both versions in one branch, we will have to merge new features into both branches and create a 3.x and a 4.x version. I will do this for the master in the coming days.

If we use the master for everything up to 4.4, then we have to create a 5.x branch for Symfony 5. This would not solve the problem. We would still have to merge new features into both branches. Or do you see any other solution?

**Comment by ajgarlag** [comment]
My opinion is that the latest bundle version should always support the latest Symfony LTS version (if it does not depends on any new Symfony feature).

As you can see in #82, the current code is fully compatible with Symfony 4.4 without any change, so I propose to maintain two branches:
- `3.x` to support at least from previous Symfony LTS (3.4) to the latest Symfony LTS (4.4) in bugfix-only mode.
- `master` to support at least from latest Symfony LTS (4.4) to current Symfony Version (5.x). This branch should receive bugfix and new features.

With this schema, if you consider that any new feature introduced in the `master` branch can be easily backported to `3.x` and is going to be useful for bundle users, you can backport it.

**Comment by migo315** [comment]
That sounds good. I will check your PR today.
